config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_name: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :profiles, except: [:show]
  get '/profile/:id', to: "profiles#show", as: 'profile_show'
  get 'pages/home'
  root "pages#home"
  get "about-me", to: 'pages#about'
  get "contact", to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height: , width: )
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs[:name].blank? }
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image
  scope :ruby_on_rails_profile_items, -> { where(subtitle: 'Ruby on Rails')}
  after_initialize :set_defaults

  private
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '250')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized
  after_initialize :set_defaults

  private
  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '350', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :profile
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name

  def first_name
    self.name.split.first.capitalize
  end

  def last_name
    self.name.split.last.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.order(:created_at)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    elsif @blog.draft?
      @blog.published!
    end
    redirect_to blogs_url, notice: "Blog status has been updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern
  def current_user
    super || guest_user
  end

  def guest_user
    OpenStruct.new( name: "Guest User",
                    first_name: "Guest",
                    last_name: "User",
                    email: "guest@example.com"
                  )
  end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_page_defaults
  end

  def set_page_defaults
    @page_title = "Shambhavi Portfolio | My Portfolio Website"
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  layout "profile"

  def index
    @profile_items = Profile.all
  end

  def new
    @profile_item = Profile.new
    3.times { @profile_item.technologies.build }
  end

  def create
    @profile_item = Profile.new(profile_params)
    respond_to do |format|
      if @profile_item.save
        format.html { redirect_to profiles_path, notice: "Your profile is now live."}
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @profile_item.update(profile_params)
        format.html { redirect_to profiles_path, notice: "Profile was successfully updated"}
      else
        format.html { render :edit }
      end
    end
  end

  def show

  end

  def destroy
    @profile_item.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile destroyed"}
      format.json { head :no_content }
    end
  end

  private

  def set_profile
    @profile_item = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
   if current_user.is_a?(User)
     link_to 'Logout', destroy_user_session_path, method: :delete
   else
     (link_to 'Register', new_user_registration_path) +
     "<br>".html_safe +
     (link_to 'Login', new_user_session_path)
   end
  end

  def source_helper(layout_name)
    if session[:source]
      greeting = "Thanks for visiting me from #{session[:source]} and you are on #{layout_name} layout"
      content_tag(:p, greeting, class: "source-greeting")
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/blogs/_blog.html.erb
<tr>
    <td><%= blog.title %></td>
    <td><%= blog.body %></td>
    <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_blog_ruler.html.erb
<hr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs, spacer_template: "blog_ruler" %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: "top" %>

    <%= login_helper %>

    <%= yield %>
    <%= source_helper("application") %>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

    <%= render "shared/nav", location: "bottom" %>


    <%= source_helper("blog") %>

  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'profiles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>
    <%= render "shared/nav", location: "top" %>

    <%= source_helper("profile") %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Hi <%= current_user.first_name %></h1>

app/views/profiles/_form.html.erb
<h1><%= title %></h1>

<%= form_for(@profile_item) do |f| %>
  <% if @profile_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, 'error') %> prohibited this profile from being saved:</h2>
      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |t| %>
      <%= t.label :name %>
      <%= t.text_field :name %>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_profile_item.html.erb
<p><%= link_to item.title, profile_show_path(item) %></p>
<p><%= item.subtitle %></p>
<p><%= item.body %></p>
<p><%= image_tag(item.thumb_image) unless item.thumb_image.nil? %></p>
<p><%= link_to "Edit", edit_profile_path(item) %></p>
<p><%= link_to "Delete Profile Item", profile_path(item), method: :delete, data: {confirm: "Are you sure?"} %></p>
<hr>

app/views/profiles/edit.html.erb
<%= render 'form', title: "Edit this Profile Item" %>

app/views/profiles/index.html.erb
<h1>Profile Items</h1>
<%= link_to "Create New Item", new_profile_path %>
<%= render partial: "profile_item", collection: @profile_items %>

app/views/profiles/new.html.erb
<%= render 'form', title: "Create a new Profile Item" %>

app/views/profiles/show.html.erb
<%= image_tag @profile_item.main_image %>
<h1><%= @profile_item.title %></h1>
<em><%= @profile_item.subtitle %></em>
<p><%= @profile_item.body %></p>

<h2>Technologies used:</h2>
<% @profile_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Profile", profiles_path %></div>
</div>